name: "Run Empirical tests"
description: "This action dispatches a request to run tests"
author: "empirical.run"

branding:
  icon: "send"
  color: "gray-dark"

# Define your inputs here.
inputs:
  auth-key:
    description: "API key for Empirical"
    required: true
  environment:
    description: "Environment to run the tests on"
    required: true
  build-url:
    description: "URL to the application to be tested"
    required: true
  runtime-config:
    description: "Runtime config for the tests"
    required: false

runs:
  using: node20
  main: dist/index.js
