name: "Run Empirical tests"
description: "This action dispatches a request to run tests"
author: "empirical.run"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "send"
  color: "gray-dark"

# Define your inputs here.
inputs:
  auth-key:
    description: "Auth key for the application"
    required: false
  build-url:
    description: "URL to the application to be tested"
    required: true
  environment:
    description: "Environment to run the tests on"
    required: true

runs:
  using: node20
  main: dist/index.js
