name: 'The name of your action here'
description: 'Provide a description here'
author: 'empirical.run'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'send'
  color: 'gray-dark'

# Define your inputs here.
inputs:
  build-url:
    description: 'URL to the application to be tested'
    required: true

runs:
  using: node20
  main: dist/index.js
