name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-web-default:
    name: Test action for web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          build-url: "https://github.com/empirical-run/dispatch-action"
          environment: production
          runtime-config:
            foo: bar
            baz: qux
